<a href="https://colab.research.google.com/github/sairaawahid/Data-Science-in-Python-Data-Prep-EDA/blob/main/Practice/Assignment_Gathering_data_happiness_survey.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Read a File into Python

Hi there,

I hear you’re the new junior data scientist on the team. Welcome!

Our polling partners just finished collecting survey data on the happiness levels in each country. I’ve attached the file.

Can you load the data into Python and confirm the number of rows in the data and the range of the happiness scores? Then we can walk through next steps together.

Thanks!\
Anna

*Attachment: happiness_survey_data.csv*

### 1. Read in data from a csv file

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_survey_data.csv')

### 2. Store data in a DataFrame

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_survey_data.csv')
df

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998
3,Afghanistan,2011,3.831719,0.521104,0.495901,51.400002
4,Afghanistan,2012,3.782938,0.520637,0.530935,51.700001
...,...,...,...,...,...,...
2084,Zimbabwe,2017,3.638300,0.754147,0.752826,52.150002
2085,Zimbabwe,2018,3.616480,0.775388,0.762675,52.625000
2086,Zimbabwe,2019,2.693523,0.759162,0.631908,53.099998
2087,Zimbabwe,2020,3.159802,0.717243,0.643303,53.575001
2088,Zimbabwe,2021,3.154578,0.685151,0.667636,54.049999

### 3. Quickly explore the data in the DataFrame

In [ ]:
df.head(10)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998
3,Afghanistan,2011,3.831719,0.521104,0.495901,51.400002
4,Afghanistan,2012,3.782938,0.520637,0.530935,51.700001
5,Afghanistan,2013,3.572100,0.483552,0.577955,52.000000
6,Afghanistan,2014,3.130896,0.525568,0.508514,52.299999
7,Afghanistan,2015,3.982855,0.528597,0.388928,52.599998
8,Afghanistan,2016,4.220169,0.559072,0.522566,52.924999
9,Afghanistan,2017,2.661718,0.490880,0.427011,53.250000

In [ ]:
df.tail(10)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
2079,Zimbabwe,2012,4.955101,0.896476,0.469531,47.599998
2080,Zimbabwe,2013,4.690188,0.799274,0.575884,48.799999
2081,Zimbabwe,2014,4.184451,0.765839,0.642034,50.000000
2082,Zimbabwe,2015,3.703191,0.735800,0.667193,51.200001
2083,Zimbabwe,2016,3.735400,0.768425,0.732971,51.674999
2084,Zimbabwe,2017,3.638300,0.754147,0.752826,52.150002
2085,Zimbabwe,2018,3.616480,0.775388,0.762675,52.625000
2086,Zimbabwe,2019,2.693523,0.759162,0.631908,53.099998
2087,Zimbabwe,2020,3.159802,0.717243,0.643303,53.575001
2088,Zimbabwe,2021,3.154578,0.685151,0.667636,54.049999

In [ ]:
df.shape

(2089, 6)

In [ ]:
df.count()

country_name                        2089
year                                2089
happiness_score                     2089
social_support                      2076
freedom_to_make_life_choices        2057
healthy_life_expectancy_at_birth    2031
dtype: int64

In [ ]:
df.describe()
# Range of happiness scores = 2.2 - 8.0

,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
count,2089.000000,2089.000000,2076.000000,2057.000000,2031.000000
mean,2013.727621,5.473747,0.811542,0.745462,63.180326
std,4.455614,1.115567,0.118935,0.140751,6.948546
min,2005.000000,2.178809,0.290184,0.257534,6.720000
25%,2010.000000,4.651972,0.747664,0.651689,58.965000
50%,2014.000000,5.405246,0.834770,0.767357,64.980003
75%,2017.000000,6.294282,0.904682,0.857677,68.362499
max,2021.000000,8.018934,0.987343,0.985178,74.349998

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   country_name                      2089 non-null   object
 1   year                              2089 non-null   int64
 2   happiness_score                   2089 non-null   float64
 3   social_support                    2076 non-null   float64
 4   freedom_to_make_life_choices      2057 non-null   float64
 5   healthy_life_expectancy_at_birth  2031 non-null   float64
dtypes: float64(4), int64(1), object(1)
memory usage: 98.1+ KB