<a href="https://colab.research.google.com/github/sairaawahid/Data-Science-in-Python-Data-Prep-EDA/blob/main/Practice/Cleaning_data_run_times_student_grade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cleaning Data
**Methods/functions practiced for cleaning data, finding, removing, imputing and resolving missing data:**
1.   `to_numeric()`
2.   `str.replace()`
3.   Handle `NaN` values when using `str.replace()`
4.   `astype()`
5.   `value_counts()`
6.   `dropna()` `dropna(subset, inplace)`
7.    `isna()` `isna().sum()`
8.    `df[df.isna().any(axis=1)]`
9.    `fillna()`
10.   `loc[]`
11.   `np.where()`
12.   `map()`

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

# **1. Data Types**

In [ ]:
run_times = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Run Times.xlsx')
run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

### a. Cleaning Data

Change data type of `Fee` to `float`

In [ ]:
run_times.Fee = pd.to_numeric(run_times.Fee.str.replace('$', ''))

In [ ]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [ ]:
run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

Change data type of `Warm Up Time` to `float`

In [ ]:
pd.to_numeric(run_times['Warm Up Time'], errors='coerce')

# Call colnumn with [''] when there are spaces in column name

# Code works but required 3 value is replaced with NaN --> Try str.replace()

0    3.5
1    3.5
2    NaN
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [ ]:
run_times['Warm Up Time'].str.replace(' min', '')
# All aother values are converted to NaN --> Try astype()

0    NaN
1    NaN
2      3
3    NaN
4    NaN
Name: Warm Up Time, dtype: object

In [ ]:
run_times['Warm Up Time'].astype('str').str.replace(' min', '')

0    3.5
1    3.5
2      3
3    2.2
4      2
Name: Warm Up Time, dtype: object

In [ ]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [ ]:
run_times.Rain = run_times.Rain.astype('int')

In [ ]:
run_times.info()
run_times.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      object
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      object
 4   Run Date      5 non-null      datetime64[ns]
 5   Race Date     5 non-null      datetime64[ns]
 6   Rain          5 non-null      int64
 7   Fee           5 non-null      float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 452.0+ bytes

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,0,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,1,0.0
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,0,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,0,0.0
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,0,2.5

# **2. Missing Data**

### a. Find Missing Data

In [ ]:
# Missing data representations in Python
import numpy as np

"""
np.NaN
pd.NA
None
"""

SyntaxError: incomplete input (3079076407.py, line 3)

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Student Grades.xlsx')
df

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
81      NaN               NaN       NaN    NaN
82  Bennett               NaN       NaN    NaN
83      NaN               EDA    Junior   84.0
84    Gavin               EDA    Senior    NaN
85   Calvin               NaN       NaN  100.0

[86 rows x 4 columns]

In [ ]:
# Quickly explore the DataFrame
df.info()

# 86 entries but Non-Null Count != 86

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  84 non-null     object
 1   Class    83 non-null     object
 2   Year     80 non-null     object
 3   Grade    82 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.8+ KB

In [ ]:
df.value_counts()
# shows all the unique rows in a df with df.value_counts(dropna=True)
# Try df.value_counts(dropna=False)

Student    Class                      Year       Grade
Isaac      Intro to SQL               Sophomore  96.0     3
Abigail    Intro to Python            Freshman   89.0     1
Aaron      EDA                        Junior     85.0     1
Alexander  Intro to Python            Freshman   85.0     1
Amelia     Intro to SQL               Sophomore  90.0     1
                                                         ..
Sofia      Intro to SQL               Sophomore  79.0     1
Sophia     Freshman Seminar           Freshman   87.0     1
Victoria   Exploratory Data Analysis  Junior     90.0     1
Wyatt      Intro to SQL               Sophomore  45.0     1
Zoey       EDA                        Junior     91.0     1
Name: count, Length: 75, dtype: int64

### b. Removing Missing Data

In [ ]:
# Take a look at the unique values (including NaN) in the Year column
df.value_counts(dropna=False)

Student  Class             Year       Grade
Isaac    Intro to SQL      Sophomore  96.0     3
Aaron    EDA               Junior     85.0     1
Aiden    Intro to Python   Freshman   86.0     1
Abigail  Intro to Python   Freshman   89.0     1
Amelia   Intro to SQL      Sophomore  90.0     1
                                              ..
William  Freshman Seminar  NaN        89.0     1
Wyatt    Intro to SQL      Sophomore  45.0     1
Zoey     EDA               Junior     91.0     1
NaN      EDA               Junior     84.0     1
         NaN               NaN        NaN      1
Name: count, Length: 84, dtype: int64

In [ ]:
# Try df.value_counts(dropna=False) on a single column
df.Year.value_counts()

Year
Freshman     35
Sophomore    24
Junior       20
Senior        1
Name: count, dtype: int64

In [ ]:
df.Year.value_counts(dropna=False)

Year
Freshman     35
Sophomore    24
Junior       20
NaN           6
Senior        1
Name: count, dtype: int64

In [ ]:
# All cells that have a NaN value
df.isna()

    Student  Class   Year  Grade
0     False  False  False  False
1     False  False  False  False
2     False  False  False  False
3     False  False  False  False
4     False  False  False  False
..      ...    ...    ...    ...
81     True   True   True   True
82    False   True   True   True
83     True  False  False  False
84    False  False  False   True
85    False   True   True  False

[86 rows x 4 columns]

In [ ]:
# Finding total missing value in each column
# Return the number of NaNs in each column

df.isna().sum()

Student    2
Class      3
Year       6
Grade      4
dtype: int64

In [ ]:
# Rows with any NaNs
# See if there are missing values in each row
df.isna().any(axis=1)

# .any(axis=1) gives True(NaN)/False(no NaN) for each row

0     False
1     False
2     False
3     False
4     False
      ...
81     True
82     True
83     True
84     True
85     True
Length: 86, dtype: bool

In [ ]:
# Finding missing value in any row
df[df.isna().any(axis=1)]

# only shows rows with missing values

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
83      NaN                        EDA  Junior   84.0
84    Gavin                        EDA  Senior    NaN
85   Calvin                        NaN     NaN  100.0

In [ ]:
# Drop rows that don't have a student or class name

# All rows that has NaN in 'Student' or 'Class' columns
df[df.isna().any(axis=1)].dropna(subset=['Student', 'Class'])

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
84    Gavin                        EDA  Senior    NaN

Using `.dropna()` or `.notna()` to remove rows with NaN values does not make permanent changes to a df.
So, either:
- Save it as new df or same one, or
- Use argument `inplace=True`

`inplace=True` is used to apply changes directly to the DataFrame you are working on, rather than returning a new object.

In [ ]:
# Apply to entire DataFrame
# Save it as new df or same one

df = df.dropna(subset=['Student', 'Class'])
df

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
77    Aaron               EDA    Junior   85.0
78  Charles               EDA    Junior   93.0
79   Connor               EDA    Junior   91.0
80    Riley               EDA    Junior   87.0
84    Gavin               EDA    Senior    NaN

[82 rows x 4 columns]

In [ ]:
# Use inplace=True

df.dropna(subset=['Student', 'Class'], inplace=True)
df

/tmp/ipykernel_1325/3959930459.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=['Student', 'Class'], inplace=True)

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
77    Aaron               EDA    Junior   85.0
78  Charles               EDA    Junior   93.0
79   Connor               EDA    Junior   91.0
80    Riley               EDA    Junior   87.0
84    Gavin               EDA    Senior    NaN

[82 rows x 4 columns]

### c. Imputing Missing Data

In [ ]:
# Check the rows with missing grades
df[df.Grade.isna()]

   Student                      Class    Year  Grade
62  Landon  Exploratory Data Analysis  Junior    NaN
84   Gavin                        EDA  Senior    NaN

Fill above missing grades with mean grade

In [ ]:
df.Grade.mean()

np.float64(85.55)

In [ ]:
#Impute the NaN grades
df.Grade.fillna(df.Grade.mean(), inplace=True)
df.Grade

/tmp/ipykernel_1325/2015825990.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Grade.fillna(df.Grade.mean(), inplace=True)
/tmp/ipykernel_1325/2015825990.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Grade.fillna(df.Grade.mean(), inplace=True)

0     86.00
1     86.00
2     86.00
3     87.00
4     90.00
      ...
77    85.00
78    93.00
79    91.00
80    87.00
84    85.55
Name: Grade, Length: 82, dtype: float64

### d. Resolving Missing Data
An alternative of imputing missing data with `.loc[]` accessor to fill in a specific missing data.

In [ ]:
# Check the rows with NaNs
df[df.isna().any(axis=1)]

   Student             Class Year  Grade
7    Jacob  Freshman Seminar  NaN   88.0
8  William  Freshman Seminar  NaN   89.0
9    Ethan  Freshman Seminar  NaN   86.0

*If you're domain expert or just by looking at data, you may know what is missing value should actually be.*

In [ ]:
# Look at all Freshman Seminar students
df[df.Class == 'Freshman Seminar']

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar       NaN   88.0
8    William  Freshman Seminar       NaN   89.0
9      Ethan  Freshman Seminar       NaN   86.0
10       Ava  Freshman Seminar  Freshman   88.0
11   Michael  Freshman Seminar  Freshman   88.0

In [ ]:
# Update a specific value
df.loc[7, 'Year'] = 'Freshman'

"""
Upon running the above cell, row no. 7 will be Year = Freshman
But, instead of updating each value one by one, do it all
together using np.where().
"""

'\nUpon running the above cell, row no. 7 will be Year = Freshman\nBut, instead of updating each value one by one, do it all\ntogether using np.where().\n'

In [ ]:
# Update multiple values using np.where()
import numpy as np

df.Year = np.where(df.Year.isna(), 'Freshman', df.Year)
df.head(11)

/tmp/ipykernel_1325/1482095315.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Year = np.where(df.Year.isna(), 'Freshman', df.Year)

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar  Freshman   88.0
8    William  Freshman Seminar  Freshman   89.0
9      Ethan  Freshman Seminar  Freshman   86.0
10       Ava  Freshman Seminar  Freshman   88.0

In [ ]:
# Check the rows with NaNs
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [Student, Class, Year, Grade]
Index: []

## 3. Inconsistent Text and Typos

### a. Find inconsistent text and typos

In [ ]:
# Find inconsistencies in categorical columns
df.Class.value_counts()

Class
Intro to Python              25
Intro to SQL                 20
Freshman Seminar             12
Exploratory Data Analysis    12
EDA                          12
Python                        1
Name: count, dtype: int64

In [ ]:
# Look at Exploratory Data Analysis students vs EDA students
df[df.Class.isin(['Exploratory Data Analysis', 'EDA'])]

      Student                      Class       Year   Grade
58     Evelyn  Exploratory Data Analysis  Sophomore   89.00
59       Jack  Exploratory Data Analysis  Sophomore   84.00
60       Ella  Exploratory Data Analysis  Sophomore  200.00
61      Chloe  Exploratory Data Analysis  Sophomore   87.00
62     Landon  Exploratory Data Analysis     Junior   85.55
63  Christian  Exploratory Data Analysis     Junior   77.00
64     Jordan  Exploratory Data Analysis     Junior   83.00
65   Jonathan  Exploratory Data Analysis     Junior   82.00
66       Levi  Exploratory Data Analysis     Junior   91.00
67   Victoria  Exploratory Data Analysis     Junior   90.00
68     Aubrey  Exploratory Data Analysis     Junior   83.00
69      Jaxon  Exploratory Data Analysis     Junior   64.00
70     Julian                        EDA     Junior   95.00
71      Grace                        EDA     Junior   77.00
72     Isaiah                        EDA     Junior   88.00
73    Cameron                        EDA     Junior   72.00
74        Eli                        EDA     Junior   92.00
75      Angel                        EDA     Junior   79.00
76       Zoey                        EDA     Junior   91.00
77      Aaron                        EDA     Junior   85.00
78    Charles                        EDA     Junior   93.00
79     Connor                        EDA     Junior   91.00
80      Riley                        EDA     Junior   87.00
84      Gavin                        EDA     Senior   85.55

In [ ]:
# Look at Intro to Python students vs Python students
df[df.Class.isin(['Intro to Python', 'Python'])]

      Student            Class      Year  Grade
12  Alexander  Intro to Python  Freshman   85.0
13      Logan  Intro to Python  Freshman   85.0
14      James  Intro to Python  Freshman   82.0
15     Daniel  Intro to Python  Freshman   85.0
16     Elijah  Intro to Python  Freshman   85.0
17   Benjamin  Intro to Python  Freshman   81.0
18        Mia  Intro to Python  Freshman   80.0
19        Mia           Python  Freshman   80.0
20     Jayden  Intro to Python  Freshman   82.0
21      Aiden  Intro to Python  Freshman   86.0
22    Matthew  Intro to Python  Freshman   87.0
23      Emily  Intro to Python  Freshman   78.0
24    Jackson  Intro to Python  Freshman   88.0
25      Lucas  Intro to Python  Freshman   77.0
26      David  Intro to Python  Freshman   74.0
27     Joseph  Intro to Python  Freshman   93.0
28    Abigail  Intro to Python  Freshman   89.0
29      Avery  Intro to Python  Freshman   79.0
30    Anthony  Intro to Python  Freshman   84.0
31      Dylan  Intro to Python  Freshman   84.0
32     Andrew  Intro to Python  Freshman   94.0
33     Carter  Intro to Python  Freshman   95.0
34     Samuel  Intro to Python  Freshman   83.0
35    Gabriel  Intro to Python  Freshman   82.0
36     Joshua  Intro to Python  Freshman   71.0
37       John  Intro to Python  Freshman   50.0

In [ ]:
df.Year.value_counts()

Year
Freshman     38
Sophomore    24
Junior       19
Senior        1
Name: count, dtype: int64

In [ ]:
# Find inconsistencies in numerical columns
df.Grade.describe()

count     82.000000
mean      85.550000
std       15.443965
min       45.000000
25%       81.000000
50%       85.275000
75%       89.750000
max      200.000000
Name: Grade, dtype: float64

*In above decsriptive stats, min-max range is unrealistic.*

In [ ]:
# Find which row has grade above 100
df[df.Grade > 100]

   Student                      Class       Year  Grade
60    Ella  Exploratory Data Analysis  Sophomore  200.0

### b. Handle inconsistent text and typos

In [ ]:
# Remember our DataFrame
df.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [ ]:
# Check the unique class values
df.Class.value_counts()

Class
Intro to Python              25
Intro to SQL                 20
Freshman Seminar             12
Exploratory Data Analysis    12
EDA                          12
Python                        1
Name: count, dtype: int64

In [ ]:
# Replace EDA with Exploratory Data Analysis
np.where(df.Class == 'EDA', 'Exploratory Data Analysis', df.Class)

array(['Freshman Seminar', 'Freshman Seminar', 'Freshman Seminar',
       'Freshman Seminar', 'Freshman Seminar', 'Freshman Seminar',
       'Freshman Seminar', 'Freshman Seminar', 'Freshman Seminar',
       'Freshman Seminar', 'Freshman Seminar', 'Freshman Seminar',
       'Intro to Python', 'Intro to Python', 'Intro to Python',
       'Intro to Python', 'Intro to Python', 'Intro to Python',
       'Intro to Python', 'Python', 'Intro to Python', 'Intro to Python',
       'Intro to Python', 'Intro to Python', 'Intro to Python',
       'Intro to Python', 'Intro to Python', 'Intro to Python',
       'Intro to Python', 'Intro to Python', 'Intro to Python',
       'Intro to Python', 'Intro to Python', 'Intro to Python',
       'Intro to Python', 'Intro to Python', 'Intro to Python',
       'Intro to Python', 'Intro to SQL', 'Intro to SQL', 'Intro to SQL',
       'Intro to SQL', 'Intro to SQL', 'Intro to SQL', 'Intro to SQL',
       'Intro to SQL', 'Intro to SQL', 'Intro to SQL', 'Intro to SQL',
       'Intro to SQL', 'Intro to SQL', 'Intro to SQL', 'Intro to SQL',
       'Intro to SQL', 'Intro to SQL', 'Intro to SQL', 'Intro to SQL',
       'Intro to SQL', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis', 'Exploratory Data Analysis',
       'Exploratory Data Analysis'], dtype=object)

In [ ]:
# np.where doesn't change the DataFrame. So save it to original df.
df.Class = np.where(df.Class == 'EDA', 'Exploratory Data Analysis', df.Class)
df.Class.value_counts()

/tmp/ipykernel_1325/3219665048.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Class = np.where(df.Class == 'EDA', 'Exploratory Data Analysis', df.Class)

Class
Intro to Python              25
Exploratory Data Analysis    24
Intro to SQL                 20
Freshman Seminar             12
Python                        1
Name: count, dtype: int64

In [ ]:
# Replace Python with Intro to Python
df.Class = np.where(df.Class == 'Python', 'Intro to Python', df.Class)
df.Class.value_counts()

/tmp/ipykernel_1325/406784448.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Class = np.where(df.Class == 'Python', 'Intro to Python', df.Class)

Class
Intro to Python              26
Exploratory Data Analysis    24
Intro to SQL                 20
Freshman Seminar             12
Name: count, dtype: int64

In [ ]:
# Replace the 200 value with 100
df.Grade = np.where(df.Grade > 100, 100, df.Grade)
df.Grade

/tmp/ipykernel_1325/1288795220.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Grade = np.where(df.Grade > 100, 100, df.Grade)

0     86.00
1     86.00
2     86.00
3     87.00
4     90.00
      ...
77    85.00
78    93.00
79    91.00
80    87.00
84    85.55
Name: Grade, Length: 82, dtype: float64

In [ ]:
df.Grade.describe()

count     82.000000
mean      84.330488
std        8.824663
min       45.000000
25%       81.000000
50%       85.275000
75%       89.750000
max      100.000000
Name: Grade, dtype: float64

### c. Map values

In [ ]:
# Read original Student Grade data
df = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Student Grades.xlsx')
df.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [ ]:
df.Class.value_counts()

Student    Class                      Year       Grade
Isaac      Intro to SQL               Sophomore  96.0     3
Abigail    Intro to Python            Freshman   89.0     1
Aaron      EDA                        Junior     85.0     1
Alexander  Intro to Python            Freshman   85.0     1
Amelia     Intro to SQL               Sophomore  90.0     1
                                                         ..
Sofia      Intro to SQL               Sophomore  79.0     1
Sophia     Freshman Seminar           Freshman   87.0     1
Victoria   Exploratory Data Analysis  Junior     90.0     1
Wyatt      Intro to SQL               Sophomore  45.0     1
Zoey       EDA                        Junior     91.0     1
Name: count, Length: 75, dtype: int64

In [ ]:
class_mapping = {'EDA' : 'Exploratory Data Analysis',
                 'Exploratory Data Analysis' : 'Exploratory Data Analysis',
                 'Python' : 'Intro to Python',
                 'Intro to Python' : 'Intro to Python',
                 'Intro to SQL' : 'Intro to SQL',
                 'Freshman Seminar' : 'Freshman Seminar'}

In [ ]:
df.Class = df.Class.map(class_mapping)
df.Class.value_counts()

Class
Intro to Python              26
Exploratory Data Analysis    25
Intro to SQL                 20
Freshman Seminar             12
Name: count, dtype: int64

### d. Clean Text Data

In [ ]:
run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

Clean `Location` column by removing `'the'` and `""`, make all characters lowercase.

In [ ]:
run_times.Location.str.strip('""').str.lower().str.replace('the', '')

0    “school”
1      school
2      “ gym”
3    “school”
4       “gym”
Name: Location, dtype: object

Nothing is stripped because `" "` is different than `“ ”` used in data.
Copy it from the df and paste in `str.strip()`.

In [ ]:
run_times.Location.str.strip('“”').str.lower().str.replace('the', '')

0    school
1    school
2       gym
3    school
4       gym
Name: Location, dtype: object

In [ ]:
# Save to original df
run_times.Location = run_times.Location.str.strip('“”').str.lower().str.replace('the', '')

In [ ]:
run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,school,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,school,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,gym,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,school,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,gym,2023-05-10 16:30:00,2023-06-15,False,$2.50