<a href="https://colab.research.google.com/github/sairaawahid/Data-Science-in-Python-Data-Prep-and-EDA/blob/main/5.%20Preparing%20for%20Modeling/Preparing_for_modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparing for Modeling
**Methods/functions practiced for transforming data into structure + format that can be used as a direct input for a machine learning algorithm:**
1.   `pd.concat()`
2.   `.merge(right, how, left_on, right_on, on)`

**Datasets:**


1.   happiness_data_ca.txt
2.   happiness_data_mx.txt
3.   happiness_data_us.txt
4.   happiness_data_cr.txt
5.   Sales Tables.xlsx

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Mounted at /content/drive

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## 1. Concat

In [3]:
# Read in text files
import pandas as pd

ca = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_data_ca.txt')
mx = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_data_mx.txt')
us = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_data_us.txt')
cr = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_data_cr.txt')

In [4]:
# Canada data
ca.head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003

In [5]:
# Mexico data
mx.head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Mexico,2005,6.580658,0.902808,0.813745,64.400002
1,Mexico,2007,6.525378,0.878806,0.670430,64.680000
2,Mexico,2008,6.829036,0.876328,0.677477,64.820000
3,Mexico,2009,6.962819,0.868221,0.682463,64.959999
4,Mexico,2010,6.802389,0.876390,0.778121,65.099998

In [6]:
# US data
us.head()

# Last column (healthy_life_expectancy_at_birth) is missing

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices
0,United States,2006,7.181794,0.964572,0.911496
1,United States,2007,7.512688,NaN,0.871904
2,United States,2008,7.280386,0.952587,0.877956
3,United States,2009,7.158032,0.911794,0.830684
4,United States,2010,7.163616,0.926159,0.828044

In [7]:
# Costa Rica data
cr.head()

# First column has different name

,nombre del país,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Costa Rica,2006,7.082465,0.936938,0.882420,68.559998
1,Costa Rica,2007,7.432132,0.917678,0.922736,68.720001
2,Costa Rica,2008,6.850680,0.915759,0.912006,68.879997
3,Costa Rica,2009,7.614929,0.899782,0.886061,69.040001
4,Costa Rica,2010,7.271054,0.915141,0.881030,69.199997

In [8]:
# Concatenate files with same column names
pd.concat([ca, mx]).head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003

In [9]:
# Concatenate files with different number of columns
pd.concat([ca, mx, us]).tail()

# NaN for missing healthy_life_expectancy_at_birth column in US data

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
11,United States,2017,6.991759,0.921003,0.868497,NaN
12,United States,2018,6.882685,0.903856,0.824607,NaN
13,United States,2019,6.943701,0.916691,0.836139,NaN
14,United States,2020,7.028088,0.937370,0.850447,NaN
15,United States,2021,6.959088,0.920009,0.815735,NaN

In [10]:
# Concatenate files with different column names
pd.concat([ca, mx, us, cr]).tail()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,nombre del país
11,NaN,2017,7.225182,0.921697,0.935618,70.0,Costa Rica
12,NaN,2018,7.141075,0.875872,0.941888,70.0,Costa Rica
13,NaN,2019,6.997619,0.906077,0.926830,70.0,Costa Rica
14,NaN,2020,6.338472,0.834200,0.889400,70.0,Costa Rica
15,NaN,2021,6.408448,0.876052,0.886652,70.0,Costa Rica

In [12]:
# Rename the column with a different name
happiness_scores = pd.concat([ca, mx, us, cr.rename(columns = {'nombre del país': 'country_name'})])
happiness_scores

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003
...,...,...,...,...,...,...
11,Costa Rica,2017,7.225182,0.921697,0.935618,70.000000
12,Costa Rica,2018,7.141075,0.875872,0.941888,70.000000
13,Costa Rica,2019,6.997619,0.906077,0.926830,70.000000
14,Costa Rica,2020,6.338472,0.834200,0.889400,70.000000
15,Costa Rica,2021,6.408448,0.876052,0.886652,70.000000

In [13]:
# Reset the index
happiness_scores.reset_index(drop=True)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003
...,...,...,...,...,...,...
59,Costa Rica,2017,7.225182,0.921697,0.935618,70.000000
60,Costa Rica,2018,7.141075,0.875872,0.941888,70.000000
61,Costa Rica,2019,6.997619,0.906077,0.926830,70.000000
62,Costa Rica,2020,6.338472,0.834200,0.889400,70.000000
63,Costa Rica,2021,6.408448,0.876052,0.886652,70.000000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## 2. Merge

### a. Merge Basics

In [15]:
# Read in spreadsheet
sales_may = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Sales Tables.xlsx', sheet_name=0)
sales_june = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Sales Tables.xlsx', sheet_name=1)
regions = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Sales Tables.xlsx', sheet_name=2)

In [16]:
sales_may

        date  store  sales
0 2022-05-01      1    341
1 2022-05-01      2    291
2 2022-05-01      3    493
3 2022-05-01      4    428
4 2022-05-01      5    152

In [17]:
regions

   store region
0      2  North
1      3   East
2      4   West
3      8  South

In [18]:
# Accept defaults
sales_may.merge(regions)

        date  store  sales region
0 2022-05-01      2    291  North
1 2022-05-01      3    493   East
2 2022-05-01      4    428   West

What's happening here is inner join.
It joins by common cloumn of `store` but only includes stores that are in both tables.
But I want to keep all the rows in the left table.

In [19]:
# Specify join
sales_may.merge(regions, how='left')

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN

In [20]:
# Specify left and right join columns
sales_may.merge(regions, how='left', left_on='store', right_on='store')

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN

*   `left_on` and `right_on` arguments are more useful when column we want to join on have different names.
*   Use `on` argument only if column we want to join on have same names.
*   It is also possible to join to multiple columns. If tables have two columns with common values, specify both in `left_on` and `right_on` arguments as a list.

In [21]:
# Use on if columns have same name
sales_may.merge(regions, how='left', on='store')

# More efficient code

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN