<a href="https://colab.research.google.com/github/sairaawahid/Data-Science-in-Python-Data-Prep-and-EDA/blob/main/5.%20Preparing%20for%20Modeling/Preparing_for_modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparing for Modeling
**Methods/functions practiced for transforming data into structure + format that can be used as a direct input for a machine learning algorithm:**
1.   `concat()` vertically + horizontally
2.   `rename()`
3.   `merge(right, how, left_on, right_on, on)`
4.   `groupby()`
5.   `fillna()`
6.   `rename()`
7.   `get_dummies()`

**Datasets:**
1.   happiness_data_ca.txt
2.   happiness_data_mx.txt
3.   happiness_data_us.txt
4.   happiness_data_cr.txt
5.   Sales Tables.xlsx
6.   [List of countries and dependencies by population (United Nations)](https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population_(United_Nations))
7.   online_shop.db

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Mounted at /content/drive

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## 1. Concat
*For appending/verticall stacking*

In [2]:
# Read in text files
import pandas as pd

ca = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_data_ca.txt')
mx = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_data_mx.txt')
us = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_data_us.txt')
cr = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/happiness_data_cr.txt')

In [3]:
# Canada data
ca.head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003

In [4]:
# Mexico data
mx.head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Mexico,2005,6.580658,0.902808,0.813745,64.400002
1,Mexico,2007,6.525378,0.878806,0.670430,64.680000
2,Mexico,2008,6.829036,0.876328,0.677477,64.820000
3,Mexico,2009,6.962819,0.868221,0.682463,64.959999
4,Mexico,2010,6.802389,0.876390,0.778121,65.099998

In [5]:
# US data
us.head()

# Last column (healthy_life_expectancy_at_birth) is missing

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices
0,United States,2006,7.181794,0.964572,0.911496
1,United States,2007,7.512688,NaN,0.871904
2,United States,2008,7.280386,0.952587,0.877956
3,United States,2009,7.158032,0.911794,0.830684
4,United States,2010,7.163616,0.926159,0.828044

In [6]:
# Costa Rica data
cr.head()

# First column has different name

,nombre del país,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Costa Rica,2006,7.082465,0.936938,0.882420,68.559998
1,Costa Rica,2007,7.432132,0.917678,0.922736,68.720001
2,Costa Rica,2008,6.850680,0.915759,0.912006,68.879997
3,Costa Rica,2009,7.614929,0.899782,0.886061,69.040001
4,Costa Rica,2010,7.271054,0.915141,0.881030,69.199997

In [7]:
# Concatenate files with same column names
pd.concat([ca, mx]).head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003

In [8]:
# Concatenate files with different number of columns
pd.concat([ca, mx, us]).tail()

# NaN for missing healthy_life_expectancy_at_birth column in US data

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
11,United States,2017,6.991759,0.921003,0.868497,NaN
12,United States,2018,6.882685,0.903856,0.824607,NaN
13,United States,2019,6.943701,0.916691,0.836139,NaN
14,United States,2020,7.028088,0.937370,0.850447,NaN
15,United States,2021,6.959088,0.920009,0.815735,NaN

In [9]:
# Concatenate files with different column names
pd.concat([ca, mx, us, cr]).tail()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,nombre del país
11,NaN,2017,7.225182,0.921697,0.935618,70.0,Costa Rica
12,NaN,2018,7.141075,0.875872,0.941888,70.0,Costa Rica
13,NaN,2019,6.997619,0.906077,0.926830,70.0,Costa Rica
14,NaN,2020,6.338472,0.834200,0.889400,70.0,Costa Rica
15,NaN,2021,6.408448,0.876052,0.886652,70.0,Costa Rica

In [10]:
# Rename the column with a different name
happiness_scores = pd.concat([ca, mx, us, cr.rename(columns = {'nombre del país': 'country_name'})])
happiness_scores

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003
...,...,...,...,...,...,...
11,Costa Rica,2017,7.225182,0.921697,0.935618,70.000000
12,Costa Rica,2018,7.141075,0.875872,0.941888,70.000000
13,Costa Rica,2019,6.997619,0.906077,0.926830,70.000000
14,Costa Rica,2020,6.338472,0.834200,0.889400,70.000000
15,Costa Rica,2021,6.408448,0.876052,0.886652,70.000000

In [11]:
# Reset the index
happiness_scores.reset_index(drop=True)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003
...,...,...,...,...,...,...
59,Costa Rica,2017,7.225182,0.921697,0.935618,70.000000
60,Costa Rica,2018,7.141075,0.875872,0.941888,70.000000
61,Costa Rica,2019,6.997619,0.906077,0.926830,70.000000
62,Costa Rica,2020,6.338472,0.834200,0.889400,70.000000
63,Costa Rica,2021,6.408448,0.876052,0.886652,70.000000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## 2. Merge
*For joining/horizontal joining*

### a. Merge Basics

In [12]:
# Read in spreadsheet
sales_may = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Sales Tables.xlsx', sheet_name=0)
sales_june = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Sales Tables.xlsx', sheet_name=1)
regions = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Sales Tables.xlsx', sheet_name=2)

In [13]:
sales_may

        date  store  sales
0 2022-05-01      1    341
1 2022-05-01      2    291
2 2022-05-01      3    493
3 2022-05-01      4    428
4 2022-05-01      5    152

In [14]:
regions

   store region
0      2  North
1      3   East
2      4   West
3      8  South

In [15]:
# Accept defaults
sales_may.merge(regions)

        date  store  sales region
0 2022-05-01      2    291  North
1 2022-05-01      3    493   East
2 2022-05-01      4    428   West

What's happening here is ***inner*** join.
It joins by common cloumn of `store` but only includes stores that are in both tables.
But I want to keep all the rows in the left table.

In [16]:
# Specify join
sales_may.merge(regions, how='left')

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN

In [17]:
# Specify left and right join columns
sales_may.merge(regions, how='left', left_on='store', right_on='store')

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN

*   `left_on` and `right_on` arguments are more useful when column we want to join on have different names.
*   Use `on` argument only if column we want to join on have same names.
*   It is also possible to join to multiple columns. If tables have two columns with common values, specify both in `left_on` and `right_on` arguments as a list.

In [18]:
# Use on if columns have same name
sales_may.merge(regions, how='left', on='store')

# More efficient code

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN

### b. Join Types

In [19]:
# Only look at 2020's happiness scores data
happiness_scores = happiness_scores[happiness_scores.year > 2019]
happiness_scores

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
14,Canada,2020,7.024905,0.930611,0.886892,71.349998
15,Canada,2021,6.939435,0.926076,0.898229,71.400002
14,Mexico,2020,5.964221,0.778816,0.873347,65.800003
15,Mexico,2021,5.990751,0.778605,0.837159,65.800003
14,United States,2020,7.028088,0.937370,0.850447,NaN
15,United States,2021,6.959088,0.920009,0.815735,NaN
14,Costa Rica,2020,6.338472,0.834200,0.889400,70.000000
15,Costa Rica,2021,6.408448,0.876052,0.886652,70.000000

In [20]:
import requests

url = 'https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population_(United_Nations)'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

response = requests.get(url, headers=headers)
population = pd.read_html(response.text)[0]
display(population.head())

/tmp/ipykernel_5241/1000693987.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  population = pd.read_html(response.text)[0]

,Country or territory,Population (1 July 2022),Population (1 July 2023),Change (%),UN continental region[1],UN statistical subregion[1]
0,World,8021407192,8091734930,+0.88%,–,–
1,India,1425423212,1438069596,+0.89%,Asia,Southern Asia
2,China[a],1425179569,1422584933,−0.18%,Asia,Eastern Asia
3,United States,341534046,343477335,+0.57%,Americas,Northern America
4,Indonesia,278830529,281190067,+0.85%,Asia,South-eastern Asia

In [21]:
population = population[population['UN statistical subregion[1]'] == 'Northern America']
population

,Country or territory,Population (1 July 2022),Population (1 July 2023),Change (%),UN continental region[1],UN statistical subregion[1]
3,United States,341534046,343477335,+0.57%,Americas,Northern America
38,Canada,38821259,39299105,+1.23%,Americas,Northern America
207,Bermuda (United Kingdom),64749,64698,−0.08%,Americas,Northern America
209,Greenland (Denmark),54990,55922,+1.69%,Americas,Northern America
231,Saint Pierre and Miquelon (France),5732,5681,−0.89%,Americas,Northern America

### i. Inner Join

In [22]:
# Merge the happiness scores and population data together
happiness_scores.merge(population, how='inner', left_on='country_name', right_on='Country or territory')

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,Country or territory,Population (1 July 2022),Population (1 July 2023),Change (%),UN continental region[1],UN statistical subregion[1]
0,Canada,2020,7.024905,0.930611,0.886892,71.349998,Canada,38821259,39299105,+1.23%,Americas,Northern America
1,Canada,2021,6.939435,0.926076,0.898229,71.400002,Canada,38821259,39299105,+1.23%,Americas,Northern America
2,United States,2020,7.028088,0.937370,0.850447,NaN,United States,341534046,343477335,+0.57%,Americas,Northern America
3,United States,2021,6.959088,0.920009,0.815735,NaN,United States,341534046,343477335,+0.57%,Americas,Northern America

### ii. Outer Join

In [23]:
happiness_scores.merge(population, how='outer', left_on='country_name', right_on='Country or territory')

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,Country or territory,Population (1 July 2022),Population (1 July 2023),Change (%),UN continental region[1],UN statistical subregion[1]
0,NaN,NaN,NaN,NaN,NaN,NaN,Bermuda (United Kingdom),64749.0,64698.0,−0.08%,Americas,Northern America
1,Canada,2020.0,7.024905,0.930611,0.886892,71.349998,Canada,38821259.0,39299105.0,+1.23%,Americas,Northern America
2,Canada,2021.0,6.939435,0.926076,0.898229,71.400002,Canada,38821259.0,39299105.0,+1.23%,Americas,Northern America
3,Costa Rica,2020.0,6.338472,0.834200,0.889400,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
4,Costa Rica,2021.0,6.408448,0.876052,0.886652,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,Greenland (Denmark),54990.0,55922.0,+1.69%,Americas,Northern America
6,Mexico,2020.0,5.964221,0.778816,0.873347,65.800003,NaN,NaN,NaN,NaN,NaN,NaN
7,Mexico,2021.0,5.990751,0.778605,0.837159,65.800003,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,Saint Pierre and Miquelon (France),5732.0,5681.0,−0.89%,Americas,Northern America
9,United States,2020.0,7.028088,0.937370,0.850447,NaN,United States,341534046.0,343477335.0,+0.57%,Americas,Northern America
10,United States,2021.0,6.959088,0.920009,0.815735,NaN,United States,341534046.0,343477335.0,+0.57%,Americas,Northern America

### iii. Left Join

In [24]:
happiness_scores.merge(population, how='left', left_on='country_name', right_on='Country or territory')

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,Country or territory,Population (1 July 2022),Population (1 July 2023),Change (%),UN continental region[1],UN statistical subregion[1]
0,Canada,2020,7.024905,0.930611,0.886892,71.349998,Canada,38821259.0,39299105.0,+1.23%,Americas,Northern America
1,Canada,2021,6.939435,0.926076,0.898229,71.400002,Canada,38821259.0,39299105.0,+1.23%,Americas,Northern America
2,Mexico,2020,5.964221,0.778816,0.873347,65.800003,NaN,NaN,NaN,NaN,NaN,NaN
3,Mexico,2021,5.990751,0.778605,0.837159,65.800003,NaN,NaN,NaN,NaN,NaN,NaN
4,United States,2020,7.028088,0.937370,0.850447,NaN,United States,341534046.0,343477335.0,+0.57%,Americas,Northern America
5,United States,2021,6.959088,0.920009,0.815735,NaN,United States,341534046.0,343477335.0,+0.57%,Americas,Northern America
6,Costa Rica,2020,6.338472,0.834200,0.889400,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
7,Costa Rica,2021,6.408448,0.876052,0.886652,70.000000,NaN,NaN,NaN,NaN,NaN,NaN

### iv. Right Join

In [25]:
happiness_scores.merge(population, how='right', left_on='country_name', right_on='Country or territory')

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,Country or territory,Population (1 July 2022),Population (1 July 2023),Change (%),UN continental region[1],UN statistical subregion[1]
0,United States,2020.0,7.028088,0.937370,0.850447,NaN,United States,341534046,343477335,+0.57%,Americas,Northern America
1,United States,2021.0,6.959088,0.920009,0.815735,NaN,United States,341534046,343477335,+0.57%,Americas,Northern America
2,Canada,2020.0,7.024905,0.930611,0.886892,71.349998,Canada,38821259,39299105,+1.23%,Americas,Northern America
3,Canada,2021.0,6.939435,0.926076,0.898229,71.400002,Canada,38821259,39299105,+1.23%,Americas,Northern America
4,NaN,NaN,NaN,NaN,NaN,NaN,Bermuda (United Kingdom),64749,64698,−0.08%,Americas,Northern America
5,NaN,NaN,NaN,NaN,NaN,NaN,Greenland (Denmark),54990,55922,+1.69%,Americas,Northern America
6,NaN,NaN,NaN,NaN,NaN,NaN,Saint Pierre and Miquelon (France),5732,5681,−0.89%,Americas,Northern America

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## 3. Create a Single Table

In [26]:
# Connect to a sql database
import sqlite3
conn = sqlite3.connect('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/online_shop.db')

In [27]:
# View the transactions table
transactions = pd.read_sql('SELECT * FROM transactions', conn)
transactions.head()

  customer  item_id purchase_date
0      Ava     1011        4/1/23
1      Ava     1014        4/1/23
2      Ava     1015       4/15/23
3      Ava     1018        5/1/23
4      Ben     2345       4/15/23

In [28]:
# View the items table
items = pd.read_sql('SELECT * FROM items', conn)
items.head()

   item_id item_description    price       category rating
0     1011            Paint  $15.99   Arts & Crafts    3.5
1     1012          Crayons   $2.87   Arts & Crafts    4.7
2     1013          Markers   $2.50   Arts & Crafts    4.8
3     1014            Brush   $1.99   Arts & Crafts    4.2
4     1015            Paper  $22.49   Arts & Crafts    4.5

In [29]:
df = transactions.merge(items, how='left', on='item_id')
df

,customer,item_id,purchase_date,item_description,price,category,rating
0,Ava,1011,4/1/23,Paint,$15.99,Arts & Crafts,3.5
1,Ava,1014,4/1/23,Brush,$1.99,Arts & Crafts,4.2
2,Ava,1015,4/15/23,Paper,$22.49,Arts & Crafts,4.5
3,Ava,1018,5/1/23,Scissors,$3.50,Arts & Crafts,4.6
4,Ben,2345,4/15/23,Dog Food,$29.99,Pet Supplies,4.9
...,...,...,...,...,...,...,...
105,Jenny,1011,4/20/23,Paint,$15.99,Arts & Crafts,3.5
106,Jenny,1014,4/20/23,Brush,$1.99,Arts & Crafts,4.2
107,Jenny,1018,4/20/23,Scissors,$3.50,Arts & Crafts,4.6
108,Jenny,1012,4/20/23,Crayons,$2.87,Arts & Crafts,4.7
109,Jenny,1015,4/20/23,Paper,$22.49,Arts & Crafts,4.5

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## 4. Prepare Rows for Modeling

In [30]:
# Goal: Predict which customers are most likely to buy dog food in June
## Each row should contain data for one customer
## y: June dog food purchases
## x: Aggregation based on April and May data

In [31]:
# Check data types
df.dtypes

customer            object
item_id              int64
purchase_date       object
item_description    object
price               object
category            object
rating              object
dtype: object

In [32]:
# Convert data types to datetime and numeric fields
df.purchase_date = pd.to_datetime(df.purchase_date)
df.price = pd.to_numeric(df.price.str.replace('$', ''))
df.rating = pd.to_numeric(df.rating)

/tmp/ipykernel_5241/206798977.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df.purchase_date = pd.to_datetime(df.purchase_date)

In [33]:
# Check updated data types
df.dtypes

customer                    object
item_id                      int64
purchase_date       datetime64[ns]
item_description            object
price                      float64
category                    object
rating                     float64
dtype: object

In [34]:
# Create a subset of April and May data
df_april_may = df[df.purchase_date.dt.month < 6]
df_april_may.head()

,customer,item_id,purchase_date,item_description,price,category,rating
0,Ava,1011,2023-04-01,Paint,15.99,Arts & Crafts,3.5
1,Ava,1014,2023-04-01,Brush,1.99,Arts & Crafts,4.2
2,Ava,1015,2023-04-15,Paper,22.49,Arts & Crafts,4.5
3,Ava,1018,2023-05-01,Scissors,3.50,Arts & Crafts,4.6
4,Ben,2345,2023-04-15,Dog Food,29.99,Pet Supplies,4.9

In [35]:
# create a subset of June data
df_june = df[df.purchase_date.dt.month == 6]
df_june.head()

,customer,item_id,purchase_date,item_description,price,category,rating
6,Ben,2345,2023-06-15,Dog Food,29.99,Pet Supplies,4.9
12,Chloe,2345,2023-06-06,Dog Food,29.99,Pet Supplies,4.9
24,Blake,2545,2023-06-10,Cat Food,25.55,Pet Supplies,4.2
34,Maxwell,5674,2023-06-02,Video Game,30.99,Games & Toys,4.1
36,Isabel,3811,2023-06-15,Socks,7.50,Apparel,3.7

In [36]:
# Create a column of june dog food purchases
dog_food_rows = df_june[df_june.item_description == 'Dog Food']
dog_food_rows

,customer,item_id,purchase_date,item_description,price,category,rating
6,Ben,2345,2023-06-15,Dog Food,29.99,Pet Supplies,4.9
12,Chloe,2345,2023-06-06,Dog Food,29.99,Pet Supplies,4.9
41,Olivia,2345,2023-06-01,Dog Food,29.99,Pet Supplies,4.9
57,Aiden,2345,2023-06-04,Dog Food,29.99,Pet Supplies,4.9
70,Lia,2345,2023-06-20,Dog Food,29.99,Pet Supplies,4.9
72,Calvin,2345,2023-06-16,Dog Food,29.99,Pet Supplies,4.9
103,Lily,2345,2023-06-18,Dog Food,29.99,Pet Supplies,4.9

In [37]:
june_dog_food_purchases = (dog_food_rows
                           .groupby('customer')['item_id']
                           .count()
                           .rename('june_dog_food_purchases'))
june_dog_food_purchases

customer
Aiden     1
Ben       1
Calvin    1
Chloe     1
Lia       1
Lily      1
Olivia    1
Name: june_dog_food_purchases, dtype: int64

In [38]:
# How much did each customer spend in April and May?
total_spend = (df_april_may
               .groupby('customer')['price']
               .sum()
               .rename('total_spend'))
total_spend

customer
Aiden       222.16
Ava          43.97
Ben          44.19
Bennett      27.73
Blake        25.55
Calvin       29.99
Chloe        36.33
Daniel       17.46
Evelyn       66.19
Gavin        39.47
Henry       112.42
Isabel        2.79
Jenny        49.34
Kate         83.25
Lia          78.95
Lily         69.31
Madeline    122.63
Margaret      7.99
Maxwell      78.31
Nolan        67.51
Olivia       68.03
Sophie        2.57
Name: total_spend, dtype: float64

In [39]:
# Concat june_dog_food_purchases and total_spend horizonatally
# Fill any NaN values with 0
model_df = (pd.concat([june_dog_food_purchases, total_spend], axis=1)
            .fillna(0)
            .reset_index())
model_df

# Each row now represents a customer. 'model_df' is ready for modeling!

    customer  june_dog_food_purchases  total_spend
0      Aiden                      1.0       222.16
1        Ben                      1.0        44.19
2     Calvin                      1.0        29.99
3      Chloe                      1.0        36.33
4        Lia                      1.0        78.95
5       Lily                      1.0        69.31
6     Olivia                      1.0        68.03
7        Ava                      0.0        43.97
8    Bennett                      0.0        27.73
9      Blake                      0.0        25.55
10    Daniel                      0.0        17.46
11    Evelyn                      0.0        66.19
12     Gavin                      0.0        39.47
13     Henry                      0.0       112.42
14    Isabel                      0.0         2.79
15     Jenny                      0.0        49.34
16      Kate                      0.0        83.25
17  Madeline                      0.0       122.63
18  Margaret                      0.0         7.99
19   Maxwell                      0.0        78.31
20     Nolan                      0.0        67.51
21    Sophie                      0.0         2.57

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## 5. Prepare Columns for Modeling

### a. Text to Numeric (Dummy Variables)

In [ ]:
# Goal: change the category column into numeric values

In [41]:
df_april_may.head()

,customer,item_id,purchase_date,item_description,price,category,rating
0,Ava,1011,2023-04-01,Paint,15.99,Arts & Crafts,3.5
1,Ava,1014,2023-04-01,Brush,1.99,Arts & Crafts,4.2
2,Ava,1015,2023-04-15,Paper,22.49,Arts & Crafts,4.5
3,Ava,1018,2023-05-01,Scissors,3.50,Arts & Crafts,4.6
4,Ben,2345,2023-04-15,Dog Food,29.99,Pet Supplies,4.9

In [42]:
# Specify a column to get dummy variables
category_dummies = pd.get_dummies(df_april_may.category)
category_dummies

     Apparel  Arts & Crafts  Games & Toys  Personal Care  Pet Supplies
0      False           True         False          False         False
1      False           True         False          False         False
2      False           True         False          False         False
3      False           True         False          False         False
4      False          False         False          False          True
..       ...            ...           ...            ...           ...
105    False           True         False          False         False
106    False           True         False          False         False
107    False           True         False          False         False
108    False           True         False          False         False
109    False           True         False          False         False

[93 rows x 5 columns]

In [ ]:
# Combine with customer data
pd.concat([df_april_may.customer, category_dummies], axis=1)

In [47]:
# group by customer so each row is a single customer
categories = (pd.concat([df_april_may.customer, category_dummies], axis=1)
    .groupby('customer')
    .sum()
    .reset_index())
categories.head()

  customer  Apparel  Arts & Crafts  Games & Toys  Personal Care  Pet Supplies
0    Aiden        0              0             0              0             8
1      Ava        0              4             0              0             0
2      Ben        0              0             0              0             2
3  Bennett        0              5             0              0             0
4    Blake        0              0             0              0             1

In [48]:
model_df = model_df.merge(categories, how='left', on='customer')
model_df.head()

,customer,june_dog_food_purchases,total_spend,Apparel,Arts & Crafts,Games & Toys,Personal Care,Pet Supplies
0,Aiden,1.0,222.16,0,0,0,0,8
1,Ben,1.0,44.19,0,0,0,0,2
2,Calvin,1.0,29.99,0,0,0,0,1
3,Chloe,1.0,36.33,3,2,0,0,0
4,Lia,1.0,78.95,2,0,0,0,1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)