<a href="https://colab.research.google.com/github/sairaawahid/Data-Science-in-Python-Data-Prep-and-EDA/blob/main/5.%20Preparing%20for%20Modeling/Preparing_for_modeling_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignments: Preparing for Modeling
**Datasets:**
1.   Book_Sales_April.xlsx
2.   Book_Sales_May.xlsx
3.   Book_Sales_June.xlsx
4.   Book_Customers.csv

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Hi there,

We just finished collecting our Q2 book sales data. Can you help us create one giant table that includes:

* April, May and June’s book sales
* Customer data

Each table has a field called customer_id that links all the tables together.

I’ve attached four files.

Thanks!\
Brooke

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Mounted at /content/drive

## 1. Create a Single Table

In [2]:
# Read all four files into a Jupyter Notebook

april = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Book_Sales_April.xlsx')
may = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Book_Sales_May.xlsx')
june = pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Book_Sales_June.xlsx')
customers = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Book_Customers.csv')

In [3]:
# Concatenate the April, May and June book sales DataFrames
sales = pd.concat([april, may, june]).reset_index(drop=True)
sales.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02

In [4]:
# Join the newly created book sales DataFrame with the customers DataFrame on customer_id
# Which type of join do you think would work best here? ---> Left join!

In [5]:
customers.head()

   Customer ID Customer Name  Age Has School Aged Children Has_Pets
0          101     Alexander   36                      Yes       No
1          102         Mason   16                       No       No
2          103         Ethan   55                       No       No
3          104        Daniel   70                       No       No
4          105       Michael   18                       No      Yes

In [6]:
df = sales.merge(customers, how='left', on='Customer ID')
df.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date,Customer Name,Age,Has School Aged Children,Has_Pets
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01,Alexander,36,Yes,No
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01,Alexander,36,Yes,No
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02,Mason,16,No,No
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02,Mason,16,No,No
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02,Mason,16,No,No

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## 2. Prepare Rows for Modeling

Hi again,

We are trying to predict which customers will purchase a book this month.

Can you reformat the data you compiled earlier this week so that it’s ready to be input into a model, with each row representing a customer instead of a purchase?

Thanks!\
Brooke

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [7]:
# What should one row of data look like for the model?
## customer - purchased in June or not - summary stats about April and May

In [8]:
# Create a column called 'June Purchases' that sums up all purchases in June
june_purchases = (june.groupby('Customer ID')['Book']
     .count()
     .rename('June Purchases')
     .to_frame()
     .reset_index())

june_purchases.head()

   Customer ID  June Purchases
0          101               2
1          103               1
2          106               1
3          108               1
4          111               2

In [9]:
df.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date,Customer Name,Age,Has School Aged Children,Has_Pets
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01,Alexander,36,Yes,No
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01,Alexander,36,Yes,No
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02,Mason,16,No,No
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02,Mason,16,No,No
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02,Mason,16,No,No

In [10]:
df_april_may = df[df['Purchase Date'].dt.month < 6]
df_april_may.tail()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date,Customer Name,Age,Has School Aged Children,Has_Pets
26,427,106,Which Dino is Best?,Children,Non-Fiction,8.99,2.6,In Person,2023-05-22,Matthew,40,Yes,No
27,428,101,Unicorns Are The Best,Children,Fiction,4.99,2.3,Online,2023-05-23,Alexander,36,Yes,No
28,429,111,Star Battles: Part 3,Teens,Fiction,13.50,4.4,Online,2023-05-24,Carter,17,No,No
29,430,112,Our Wonderous Planet,Teens,Non-Fiction,17.75,4.5,In Person,2023-05-25,Owen,17,No,No
30,431,116,Who's There,Adults,Fiction,24.99,2.1,Online,2023-05-26,Emily,51,No,No

In [11]:
# Create a column called 'Total Spend' that sums up the prices of all the books that were purchased in April and May
total_spend = (df_april_may.groupby('Customer ID')['Price']
             .sum()
             .rename('Total Spend')
             .to_frame()
             .reset_index())
total_spend.head()

   Customer ID  Total Spend
0          101        33.71
1          102        79.96
2          103        55.20
3          104        42.32
4          105        21.50

In [12]:
# Combine the 'June Purchases' and 'Total Spend' columns into a single DataFrame for modeling
model_df = total_spend.merge(june_purchases, how='left').fillna(0)
model_df.head()

   Customer ID  Total Spend  June Purchases
0          101        33.71             2.0
1          102        79.96             0.0
2          103        55.20             1.0
3          104        42.32             0.0
4          105        21.50             0.0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## 3. Prepare Columns for Modeling

Hi again,

Thanks for your help earlier this week! We just learned that we also have to make all of the data numeric before inputting it into a predictive model.

Can you turn the Audience text field into a numeric field?

Thanks!\
Brooke

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [24]:
df_april_may.Audience.value_counts()

Audience
Adults      12
Children    10
Teens        9
Name: count, dtype: int64

In [26]:
# Change the Audience field into a dummy variable
audience_dummies = pd.get_dummies(df_april_may.Audience)
audience_dummies.head()

   Adults  Children  Teens
0   False      True  False
1   False      True  False
2   False     False   True
3   False     False   True
4   False     False   True

In [27]:
df_april_may['Customer ID'].head()

0    101
1    101
2    102
3    102
4    102
Name: Customer ID, dtype: int64

In [30]:
customer_audience = pd.concat([df_april_may['Customer ID'], audience_dummies], axis=1)
customer_audience.head()

   Customer ID  Adults  Children  Teens
0          101   False      True  False
1          101   False      True  False
2          102   False     False   True
3          102   False     False   True
4          102   False     False   True

In [36]:
# Using the Audience dummy variables, create three new columns that contain
# the number of Adult / Children / Teen books purchased by each customer
book_type = customer_audience.groupby('Customer ID').sum().reset_index()
book_type.head()

   Customer ID  Adults  Children  Teens
0          101       0         5      0
1          102       0         0      4
2          103       2         0      0
3          104       2         0      0
4          105       1         0      0

In [38]:
# Combine the three new columns back with the customer-level data
model_df.merge(book_type, how='left')

    Customer ID  Total Spend  June Purchases  Adults  Children  Teens
0           101        33.71             2.0       0         5      0
1           102        79.96             0.0       0         0      4
2           103        55.20             1.0       2         0      0
3           104        42.32             0.0       2         0      0
4           105        21.50             0.0       1         0      0
5           106        38.96             1.0       0         4      0
6           107        25.99             0.0       1         0      0
7           108         9.20             1.0       0         1      0
8           109        22.72             0.0       1         0      0
9           110        21.58             0.0       1         0      0
10          111        40.50             2.0       0         0      3
11          112        35.50             0.0       0         0      2
12          113        28.99             0.0       1         0      0
13          114        28.50             0.0       1         0      0
14          115        27.60             0.0       1         0      0
15          116        24.99             0.0       1         0      0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## 4. Feature Engineering

Hi again,

I have one final request for you.

As a reminder, our goal is to try and predict which customer will purchase a book this month.

Can you create new features that you think will do a good job making a prediction?

Thanks!\
Brooke

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [16]:
# what features could do a good job predicting june purchases?

In [17]:
# create the feature

In [18]:
# add it to the dataframe for modeling

In [19]:
# create another feature

In [20]:
# add it to the dataframe for modeling

In [21]:
# view the final dataframe that is ready to be input into a model